// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/************************************************************/
/**
 * 
 */
@Entity
@Table(name = "APP_USER")
public class User {

	@Id
	@Column(name = "username", nullable = false, updatable = false)
	private String username;
	@Column(name = "password", nullable = false)
	private String password;

	//empty constructor needed for Hibernate queries
	public User() {

	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}


	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}
