// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main;

import java.awt.EventQueue;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

import view.AppView;
import view.LoginView;
import view.RegView;

/************************************************************/
/**
 * 
 */
public class FocusApp {
	/**
				 * 
				 */
	public User[] user;
	/**
				 * 
				 */
	public City[] city;

	/**
	 * variables for database communication
	 */
	private static SessionFactory sessionFactory;
	private static Session session;
	private static LoginView loginView = null;
	private static RegView regView = null;

	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					loginView = new LoginView();
					loginView.setVisible(true);

					regView = new RegView();
					loginView.addListenerToRegBtn(a -> changeToRegView());
					regView.addListenerToBtnReg(a -> {
						addUser();
						regView.showSuccessDialog();
					});
					System.out.println("Listeners added");
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	private static void changeToRegView() { //login -> reg
		try {
			regView.setVisible(true);
			loginView.setVisible(false);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	/**
	 * 
	 * @param duration
	 * @return
	 * @return
	 */
	public void startTimer(int duration) {
	}

	/**
	 * 
	 */
	public void endTimer() {
	}

	private static void addUser() {
		User user = new User(regView.getUsername(), regView.getPassword());
		session = HibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		User u = session.find(User.class, user.getUsername());
		if (u != null) {
			throw new DuplicateUserException();
		} else {
			session.persist(user);
		}
		session.getTransaction().commit();
		if (session != null) {
			session.close();
		}
	}
}
