// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main;

/************************************************************/
/**
 * 
 */
public class FocusApp {
	/**
				 * 
				 */
				public User[] user;
	/**
				 * 
				 */
				public City[] city;

	/**
	 * 
	 * @param duration 
	 * @return 
	 * @return 
	 */
	public void startTimer(int duration) {
	}

	/**
	 * 
	 */
	public void endTimer() {
	}

	/**
	 * 
	 * @param user 
	 */
	public void addUser(User user) {
	}
}
