// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

/************************************************************/
/**
 * 
 */
public class FocusApp {
	/**
				 * 
				 */
				public User[] user;
	/**
				 * 
				 */
				public City[] city;

				/**
				 * variables for database communication
				 */
				private static SessionFactory sessionFactory;
				private Session session;
	/**
	 * 
	 * @param duration 
	 * @return 
	 * @return 
	 */
	public void startTimer(int duration) {
	}

	/**
	 * 
	 */
	public void endTimer() {
	}

	/**
	 * 
	 * @param user 
	 */
	public void addUser(User user) {
		
		session = HibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		User u = session.find(User.class, user.getUsername());
		if( u != null) {
			throw new DuplicateUserException();
		}
		else {
			session.persist(user);
		}
		session.getTransaction().commit();
		if (session != null) {
			session.close();
		}
	}
}
