// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main;

/************************************************************/
/**
 * 
 */
public class User {
	/**
				 * 
				 */
				private String id;
	/**
	 * 
	 */
	private String username;
}
