// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
				 * 
				 */
				private String id;
	/**
				 * 
				 */
				private Date timeStamp;
	/**
				 * 
				 */
				private int duration;
	/**
	 * 
	 */
	private String subject;
}
