// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class City {
	/**
				 * 
				 */
				private Building[] buildings;
	/**
				 * 
				 */
				public User user;

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
	}

	/**
	 * 
	 * @return 
	 */
	public Building[] getBuildings() {
		return null;
	}
}
