// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.List;

import org.hibernate.Session;
import main.SessionUtil;

/************************************************************/
/**
 * 
 */
public class City {
	/**
				 * 
				 */
				private List<Building> buildings;
	/**
				 * 
				 */
				//public User user;

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Building building) {
	}

	/**
	 * 
	 * @return 
	 */
	public void loadBuildings(User user) {
		Session session = SessionUtil.startSession();
		List<Building> retrievedBuildings = session.createQuery("from Building b where b.owner = :owner_username", Building.class).setParameter("owner_username", user.getUsername()).list();
		for (Building b : retrievedBuildings) {
			String password = session.createQuery("select u.password from app_user u where u.username = :owner_username", String.class).setParameter("owner_username", user.getUsername()).toString();
			b.getOwner().setPassword(password);
			buildings.add(b);
		}
		SessionUtil.endSession(session);
	}
	
	
}
