// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Timer {
	/**
				 * 
				 */
				private int duration;

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void stop() {
	}
}
